//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMStud.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMStud.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tool arguments: .
        /// </summary>
        internal static string @__Tool_arguments_ {
            get {
                return ResourceManager.GetString("__Tool_arguments_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tool ID: .
        /// </summary>
        internal static string @__Tool_ID_ {
            get {
                return ResourceManager.GetString("__Tool_ID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tool name: .
        /// </summary>
        internal static string @__Tool_name_ {
            get {
                return ResourceManager.GetString("__Tool_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string _0____1_ {
            get {
                return ResourceManager.GetString("_0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}{2}.
        /// </summary>
        internal static string _0___1__2_ {
            get {
                return ResourceManager.GetString("_0___1__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} Tok/s.
        /// </summary>
        internal static string _0_F2__Tok_s {
            get {
                return ResourceManager.GetString("_0_F2__Tok_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  s.
        /// </summary>
        internal static string _s {
            get {
                return ResourceManager.GetString("_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tokens.
        /// </summary>
        internal static string _Tokens {
            get {
                return ResourceManager.GetString("_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A changed setting requires the model to be reloaded, reload now?.
        /// </summary>
        internal static string A_changed_setting_requires_the_model_to_be_reloaded__reload_now_ {
            get {
                return ResourceManager.GetString("A_changed_setting_requires_the_model_to_be_reloaded__reload_now_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An index was out of range..
        /// </summary>
        internal static string An_index_was_out_of_range_ {
            get {
                return ResourceManager.GetString("An_index_was_out_of_range_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API server.
        /// </summary>
        internal static string API_server {
            get {
                return ResourceManager.GetString("API_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context full..
        /// </summary>
        internal static string Context_full {
            get {
                return ResourceManager.GetString("Context_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialectic enable.
        /// </summary>
        internal static string Dialectic_enable {
            get {
                return ResourceManager.GetString("Dialectic_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialecticInit.
        /// </summary>
        internal static string DialecticInit {
            get {
                return ResourceManager.GetString("DialecticInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialecticStart.
        /// </summary>
        internal static string DialecticStart {
            get {
                return ResourceManager.GetString("DialecticStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed: {0}.
        /// </summary>
        internal static string Download_failed___0_ {
            get {
                return ResourceManager.GetString("Download_failed___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed with error code: {0}.
        /// </summary>
        internal static string Download_failed_with_error_code___0_ {
            get {
                return ResourceManager.GetString("Download_failed_with_error_code___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} to:
        ///{1}.
        /// </summary>
        internal static string Downloaded__0__to___1_ {
            get {
                return ResourceManager.GetString("Downloaded__0__to___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing transcription - Press Enter to finish or Esc to cancel.
        /// </summary>
        internal static string Editing_transcription_ {
            get {
                return ResourceManager.GetString("Editing_transcription_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating context.
        /// </summary>
        internal static string Error_creating_context {
            get {
                return ResourceManager.GetString("Error_creating_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating sampler.
        /// </summary>
        internal static string Error_creating_sampler {
            get {
                return ResourceManager.GetString("Error_creating_sampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating session.
        /// </summary>
        internal static string Error_creating_session {
            get {
                return ResourceManager.GetString("Error_creating_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting message.
        /// </summary>
        internal static string Error_deleting_message {
            get {
                return ResourceManager.GetString("Error_deleting_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initialising voice input.
        /// </summary>
        internal static string Error_initialising_voice_input {
            get {
                return ResourceManager.GetString("Error_initialising_voice_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing audio capture..
        /// </summary>
        internal static string Error_initializing_audio_capture_ {
            get {
                return ResourceManager.GetString("Error_initializing_audio_capture_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading files for .
        /// </summary>
        internal static string Error_loading_files_for_ {
            get {
                return ResourceManager.GetString("Error_loading_files_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading model.
        /// </summary>
        internal static string Error_loading_model {
            get {
                return ResourceManager.GetString("Error_loading_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading VAD model..
        /// </summary>
        internal static string Error_loading_VAD_model_ {
            get {
                return ResourceManager.GetString("Error_loading_VAD_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Whisper model..
        /// </summary>
        internal static string Error_loading_Whisper_model_ {
            get {
                return ResourceManager.GetString("Error_loading_Whisper_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file: {0}.
        /// </summary>
        internal static string Error_reading_file___0_ {
            get {
                return ResourceManager.GetString("Error_reading_file___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error regenerating message.
        /// </summary>
        internal static string Error_regenerating_message {
            get {
                return ResourceManager.GetString("Error_regenerating_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting system prompt.
        /// </summary>
        internal static string Error_setting_system_prompt {
            get {
                return ResourceManager.GetString("Error_setting_system_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting voice input..
        /// </summary>
        internal static string Error_starting_voice_input {
            get {
                return ResourceManager.GetString("Error_starting_voice_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Whisper model not found..
        /// </summary>
        internal static string Error_Whisper_model_not_found {
            get {
                return ResourceManager.GetString("Error_Whisper_model_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert a token..
        /// </summary>
        internal static string Failed_to_convert_a_token_ {
            get {
                return ResourceManager.GetString("Failed_to_convert_a_token_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory: {0}.
        /// </summary>
        internal static string Failed_to_create_directory___0_ {
            get {
                return ResourceManager.GetString("Failed_to_create_directory___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the model context..
        /// </summary>
        internal static string Failed_to_create_the_model_context_ {
            get {
                return ResourceManager.GetString("Failed_to_create_the_model_context_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the sampler..
        /// </summary>
        internal static string Failed_to_create_the_sampler_ {
            get {
                return ResourceManager.GetString("Failed_to_create_the_sampler_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to tokenize the prompt..
        /// </summary>
        internal static string Failed_to_tokenize_the_prompt_ {
            get {
                return ResourceManager.GetString("Failed_to_tokenize_the_prompt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First token time: .
        /// </summary>
        internal static string First_token_time__ {
            get {
                return ResourceManager.GetString("First_token_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found.
        /// </summary>
        internal static string Folder_not_found {
            get {
                return ResourceManager.GetString("Folder_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStateData.
        /// </summary>
        internal static string GetStateData {
            get {
                return ResourceManager.GetString("GetStateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Error loading files for .
        /// </summary>
        internal static string HTTP_Error_loading_files_for_ {
            get {
                return ResourceManager.GetString("HTTP_Error_loading_files_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Parse Error for .
        /// </summary>
        internal static string JSON_Parse_Error_for_ {
            get {
                return ResourceManager.GetString("JSON_Parse_Error_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LM Stud.
        /// </summary>
        internal static string LM_Stud {
            get {
                return ResourceManager.GetString("LM_Stud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LM_Stud_256 {
            get {
                object obj = ResourceManager.GetObject("LM_Stud_256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a model first..
        /// </summary>
        internal static string Load_a_model_first_ {
            get {
                return ResourceManager.GetString("Load_a_model_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading: .
        /// </summary>
        internal static string Loading__ {
            get {
                return ResourceManager.GetString("Loading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum context size of the last loaded model: .
        /// </summary>
        internal static string Max_context_size_of_last_loaded_model {
            get {
                return ResourceManager.GetString("Max_context_size_of_last_loaded_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model search error: {0}.
        /// </summary>
        internal static string Model_search_error___0_ {
            get {
                return ResourceManager.GetString("Model_search_error___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models folder not found, please specify a valid folder in the Settings tab..
        /// </summary>
        internal static string Models_folder_not_found__please_specify_a_valid_folder_in_the_Settings_tab {
            get {
                return ResourceManager.GetString("Models_folder_not_found__please_specify_a_valid_folder_in_the_Settings_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model has been loaded..
        /// </summary>
        internal static string No_model_has_been_loaded_ {
            get {
                return ResourceManager.GetString("No_model_has_been_loaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model loaded.
        /// </summary>
        internal static string No_model_loaded {
            get {
                return ResourceManager.GetString("No_model_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item from both lists..
        /// </summary>
        internal static string Please_select_an_item_from_both_lists_ {
            get {
                return ResourceManager.GetString("Please_select_an_item_from_both_lists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retokenizing chat....
        /// </summary>
        internal static string Retokenizing_chat___ {
            get {
                return ResourceManager.GetString("Retokenizing_chat___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetStateData.
        /// </summary>
        internal static string SetStateData {
            get {
                return ResourceManager.GetString("SetStateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chat template could not be applied..
        /// </summary>
        internal static string The_chat_template_could_not_be_applied_ {
            get {
                return ResourceManager.GetString("The_chat_template_could_not_be_applied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPU is out of memory..
        /// </summary>
        internal static string The_GPU_is_out_of_memory_ {
            get {
                return ResourceManager.GetString("The_GPU_is_out_of_memory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model backend returned a decode error..
        /// </summary>
        internal static string The_model_backend_returned_a_decode_error_ {
            get {
                return ResourceManager.GetString("The_model_backend_returned_a_decode_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model could not be loaded..
        /// </summary>
        internal static string The_model_could_not_be_loaded_ {
            get {
                return ResourceManager.GetString("The_model_could_not_be_loaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modified settings are overridden by the Model Settings for this model..
        /// </summary>
        internal static string The_modified_settings_are_overridden_by_the_Model_Settings_for_this_model_ {
            get {
                return ResourceManager.GetString("The_modified_settings_are_overridden_by_the_Model_Settings_for_this_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Call.
        /// </summary>
        internal static string Tool_Call {
            get {
                return ResourceManager.GetString("Tool_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Output.
        /// </summary>
        internal static string Tool_Output {
            get {
                return ResourceManager.GetString("Tool_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Whisper VAD models..
        /// </summary>
        internal static string ToolTip_butVADDown {
            get {
                return ResourceManager.GetString("ToolTip_butVADDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the tool for creating new files under the base path..
        /// </summary>
        internal static string ToolTip_checkFileCreateEnable {
            get {
                return ResourceManager.GetString("ToolTip_checkFileCreateEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the tool for listing the contents of a folder under the base path..
        /// </summary>
        internal static string ToolTip_checkFileListEnable {
            get {
                return ResourceManager.GetString("ToolTip_checkFileListEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the tool for reading the contents of files under the base path..
        /// </summary>
        internal static string ToolTip_checkFileReadEnable {
            get {
                return ResourceManager.GetString("ToolTip_checkFileReadEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the tool for writing to files under the base path..
        /// </summary>
        internal static string ToolTip_checkFileWriteEnable {
            get {
                return ResourceManager.GetString("ToolTip_checkFileWriteEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Flash Attention. The filled state lets Llama.cpp choose automatically..
        /// </summary>
        internal static string ToolTip_checkFlashAttn {
            get {
                return ResourceManager.GetString("ToolTip_checkFlashAttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the model in RAM..
        /// </summary>
        internal static string ToolTip_checkMLock {
            get {
                return ResourceManager.GetString("ToolTip_checkMLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map the model file to memory for on-demand loading, may improve model load times..
        /// </summary>
        internal static string ToolTip_checkMMap {
            get {
                return ResourceManager.GetString("ToolTip_checkMMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak the generated responses using the computers default voice..
        /// </summary>
        internal static string ToolTip_checkSpeak {
            get {
                return ResourceManager.GetString("ToolTip_checkSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An intermediate check state (filled in) means it will transcribe spoken words without generating, when checked it will automatically generate..
        /// </summary>
        internal static string ToolTip_checkVoiceInput {
            get {
                return ResourceManager.GetString("ToolTip_checkVoiceInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMA (Non-Uniform Memory Access) strategy. Adjust if using multi-socket CPUs or specific memory configurations..
        /// </summary>
        internal static string ToolTip_comboNUMAStrat {
            get {
                return ResourceManager.GetString("ToolTip_comboNUMAStrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Whisper VAD model used for speech detection..
        /// </summary>
        internal static string ToolTip_comboVADModel {
            get {
                return ResourceManager.GetString("ToolTip_comboVADModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters controlling text generation on CPU..
        /// </summary>
        internal static string ToolTip_groupCPUParams {
            get {
                return ResourceManager.GetString("ToolTip_groupCPUParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters for the pre-generation step (batch preparation)..
        /// </summary>
        internal static string ToolTip_groupCPUParamsBatch {
            get {
                return ResourceManager.GetString("ToolTip_groupCPUParamsBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set an instruction to optimize the way the assistant uses the file tools..
        /// </summary>
        internal static string ToolTip_linkFileInstruction {
            get {
                return ResourceManager.GetString("ToolTip_linkFileInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch size for processing tokens during generation. Higher values can improve performance at the cost of higher RAM usage..
        /// </summary>
        internal static string ToolTip_numBatchSize {
            get {
                return ResourceManager.GetString("ToolTip_numBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the timeout for commands, 0 means no timeout..
        /// </summary>
        internal static string ToolTip_numCmdTimeout {
            get {
                return ResourceManager.GetString("ToolTip_numCmdTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context size (max tokens). Higher values improve memory but use more RAM..
        /// </summary>
        internal static string ToolTip_numCtxSize {
            get {
                return ResourceManager.GetString("ToolTip_numCtxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-pass filter cutoff frequency. Higher values reduce low frequency noise..
        /// </summary>
        internal static string ToolTip_numFreqThreshold {
            get {
                return ResourceManager.GetString("ToolTip_numFreqThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay before automatic response generation after speech input ends (only when ‘Speech input’ is fully enabled)..
        /// </summary>
        internal static string ToolTip_numGenDelay {
            get {
                return ResourceManager.GetString("ToolTip_numGenDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of layers to offload to GPU, more layers improve performance but increase GPU memory usage..
        /// </summary>
        internal static string ToolTip_numGPULayers {
            get {
                return ResourceManager.GetString("ToolTip_numGPULayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min-P sampling: keeps only tokens whose individual probability is at least this fraction of the top token’s probability, trimming unlikely options and reducing noise..
        /// </summary>
        internal static string ToolTip_numMinP {
            get {
                return ResourceManager.GetString("ToolTip_numMinP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tokens to generate per response (max length of the AI&apos;s reply), -1 = no limit..
        /// </summary>
        internal static string ToolTip_numNGen {
            get {
                return ResourceManager.GetString("ToolTip_numNGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition penalty reduces repetitive outputs. Higher values strongly discourage repeated phrases..
        /// </summary>
        internal static string ToolTip_numRepPen {
            get {
                return ResourceManager.GetString("ToolTip_numRepPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature controls randomness. Lower values make responses more deterministic; higher values produce more creative outputs..
        /// </summary>
        internal static string ToolTip_numTemp {
            get {
                return ResourceManager.GetString("ToolTip_numTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU threads for token generation. Typically, around 75% of your physical cores is optimal to prevent oversaturating the memory controller..
        /// </summary>
        internal static string ToolTip_numThreads {
            get {
                return ResourceManager.GetString("ToolTip_numThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU threads used for batch preparation..
        /// </summary>
        internal static string ToolTip_numThreadsBatch {
            get {
                return ResourceManager.GetString("ToolTip_numThreadsBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-K sampling: limits token choice to the K most probable tokens, improving coherency..
        /// </summary>
        internal static string ToolTip_numTopK {
            get {
                return ResourceManager.GetString("ToolTip_numTopK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-P sampling: controls diversity by choosing from the smallest possible set of tokens whose cumulative probability exceeds this threshold..
        /// </summary>
        internal static string ToolTip_numTopP {
            get {
                return ResourceManager.GetString("ToolTip_numTopP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Activity Detection threshold: for Basic VAD this sets loudness, for Whisper VAD this sets speech probability..
        /// </summary>
        internal static string ToolTip_numVadThreshold {
            get {
                return ResourceManager.GetString("ToolTip_numVadThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set how similar the detected wake word must be to activate transcription..
        /// </summary>
        internal static string ToolTip_numWakeWordSimilarity {
            get {
                return ResourceManager.GetString("ToolTip_numWakeWordSimilarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use simple energy-based voice activity detection..
        /// </summary>
        internal static string ToolTip_radioBasicVAD {
            get {
                return ResourceManager.GetString("ToolTip_radioBasicVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Whisper&apos;s neural VAD model for speech detection..
        /// </summary>
        internal static string ToolTip_radioWhisperVAD {
            get {
                return ResourceManager.GetString("ToolTip_radioWhisperVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File access is relative to this path and canonically restricted to files and folders under this path only..
        /// </summary>
        internal static string ToolTip_textFileBasePath {
            get {
                return ResourceManager.GetString("ToolTip_textFileBasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Google API key is required to use the search tool, you can get a free one for 100 searches per day..
        /// </summary>
        internal static string ToolTip_textGoogleApiKey {
            get {
                return ResourceManager.GetString("ToolTip_textGoogleApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own Google Programmable Search Engine and copy its &quot;Search engine ID&quot; here..
        /// </summary>
        internal static string ToolTip_textGoogleSearchID {
            get {
                return ResourceManager.GetString("ToolTip_textGoogleSearchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to a text file containing a Jinja template, this file must remain in place..
        /// </summary>
        internal static string ToolTip_textJinjaTmplModel {
            get {
                return ResourceManager.GetString("ToolTip_textJinjaTmplModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the folder containing your .gguf model files..
        /// </summary>
        internal static string ToolTip_textModelsPath {
            get {
                return ResourceManager.GetString("ToolTip_textModelsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell the AI who or what to be, how to respond, or provide initial context..
        /// </summary>
        internal static string ToolTip_textSystemPrompt {
            get {
                return ResourceManager.GetString("ToolTip_textSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional wake word phrase required before transcription begins..
        /// </summary>
        internal static string ToolTip_textWakeWord {
            get {
                return ResourceManager.GetString("ToolTip_textWakeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the chat message..
        /// </summary>
        internal static string Unable_to_parse_the_chat_message_ {
            get {
                return ResourceManager.GetString("Unable_to_parse_the_chat_message_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using API Model: .
        /// </summary>
        internal static string Using_API_Model_ {
            get {
                return ResourceManager.GetString("Using_API_Model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Model: .
        /// </summary>
        internal static string Using_Model_ {
            get {
                return ResourceManager.GetString("Using_Model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAD model not found, use Basic VAD?.
        /// </summary>
        internal static string VAD_model_not_found__use_Basic_VAD_ {
            get {
                return ResourceManager.GetString("VAD_model_not_found__use_Basic_VAD_", resourceCulture);
            }
        }
    }
}
