//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMStud.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMStud.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | Loaded: .
        /// </summary>
        internal static string ___Loaded__ {
            get {
                return ResourceManager.GetString("___Loaded__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tool arguments: .
        /// </summary>
        internal static string @__Tool_arguments_ {
            get {
                return ResourceManager.GetString("__Tool_arguments_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tool ID: .
        /// </summary>
        internal static string @__Tool_ID_ {
            get {
                return ResourceManager.GetString("__Tool_ID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tool name: .
        /// </summary>
        internal static string @__Tool_name_ {
            get {
                return ResourceManager.GetString("__Tool_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string _0____1_ {
            get {
                return ResourceManager.GetString("_0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}:{2}.
        /// </summary>
        internal static string _0___1___2_ {
            get {
                return ResourceManager.GetString("_0___1___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}{2}.
        /// </summary>
        internal static string _0___1__2_ {
            get {
                return ResourceManager.GetString("_0___1__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} Token/s.
        /// </summary>
        internal static string _0_F2__Tok_s {
            get {
                return ResourceManager.GetString("_0_F2__Tok_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (API model).
        /// </summary>
        internal static string _API_model_ {
            get {
                return ResourceManager.GetString("_API_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (local model).
        /// </summary>
        internal static string _local_model_ {
            get {
                return ResourceManager.GetString("_local_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (MCP server).
        /// </summary>
        internal static string _MCP_server_ {
            get {
                return ResourceManager.GetString("_MCP_server_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  s.
        /// </summary>
        internal static string _s {
            get {
                return ResourceManager.GetString("_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tokens.
        /// </summary>
        internal static string _Tokens {
            get {
                return ResourceManager.GetString("_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tool name:.
        /// </summary>
        internal static string _Tool_name_ {
            get {
                return ResourceManager.GetString("_Tool_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A changed setting requires the model to be reloaded, reload now?.
        /// </summary>
        internal static string A_changed_setting_requires_the_model_to_be_reloaded__reload_now_ {
            get {
                return ResourceManager.GetString("A_changed_setting_requires_the_model_to_be_reloaded__reload_now_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An index was out of range.
        /// </summary>
        internal static string An_index_was_out_of_range_ {
            get {
                return ResourceManager.GetString("An_index_was_out_of_range_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another slot already uses that name..
        /// </summary>
        internal static string Another_slot_already_uses_that_name_ {
            get {
                return ResourceManager.GetString("Another_slot_already_uses_that_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        internal static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API base URL is not configured..
        /// </summary>
        internal static string API_base_URL_is_not_configured_ {
            get {
                return ResourceManager.GetString("API_base_URL_is_not_configured_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Client.
        /// </summary>
        internal static string API_Client {
            get {
                return ResourceManager.GetString("API_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API endpoint not found.
        /// </summary>
        internal static string API_endpoint_not_found {
            get {
                return ResourceManager.GetString("API_endpoint_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API error ({0}): {1}.
        /// </summary>
        internal static string API_error___0_____1_ {
            get {
                return ResourceManager.GetString("API_error___0_____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API model tool slot is missing an API URL or model..
        /// </summary>
        internal static string API_model_tool_slot_is_missing_an_API_URL_or_model_ {
            get {
                return ResourceManager.GetString("API_model_tool_slot_is_missing_an_API_URL_or_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API response did not contain any message..
        /// </summary>
        internal static string API_response_did_not_contain_any_message_ {
            get {
                return ResourceManager.GetString("API_response_did_not_contain_any_message_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Server.
        /// </summary>
        internal static string API_Server {
            get {
                return ResourceManager.GetString("API_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API server could not start on port {0} because the port is already in use.
        ///
        ///{1}.
        /// </summary>
        internal static string API_server_could_not_start_on_port__ {
            get {
                return ResourceManager.GetString("API_server_could_not_start_on_port__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string Authentication_failed {
            get {
                return ResourceManager.GetString("Authentication_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold.
        /// </summary>
        internal static string Cold {
            get {
                return ResourceManager.GetString("Cold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string colon {
            get {
                return ResourceManager.GetString("colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command:.
        /// </summary>
        internal static string Command_ {
            get {
                return ResourceManager.GetString("Command_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context full..
        /// </summary>
        internal static string Context_full {
            get {
                return ResourceManager.GetString("Context_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialectic.
        /// </summary>
        internal static string Dialectic {
            get {
                return ResourceManager.GetString("Dialectic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialectic enable.
        /// </summary>
        internal static string Dialectic_enable {
            get {
                return ResourceManager.GetString("Dialectic_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialectic relay: .
        /// </summary>
        internal static string Dialectic_relay__ {
            get {
                return ResourceManager.GetString("Dialectic_relay__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed: {0}.
        /// </summary>
        internal static string Download_failed___0_ {
            get {
                return ResourceManager.GetString("Download_failed___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed with error code: {0}.
        /// </summary>
        internal static string Download_failed_with_error_code___0_ {
            get {
                return ResourceManager.GetString("Download_failed_with_error_code___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} to:
        ///{1}.
        /// </summary>
        internal static string Downloaded__0__to___1_ {
            get {
                return ResourceManager.GetString("Downloaded__0__to___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing transcription - Press Enter to finish or Esc to cancel.
        /// </summary>
        internal static string Editing_transcription_ {
            get {
                return ResourceManager.GetString("Editing_transcription_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating context.
        /// </summary>
        internal static string Error_creating_context {
            get {
                return ResourceManager.GetString("Error_creating_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating sampler.
        /// </summary>
        internal static string Error_creating_sampler {
            get {
                return ResourceManager.GetString("Error_creating_sampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting message.
        /// </summary>
        internal static string Error_deleting_message {
            get {
                return ResourceManager.GetString("Error_deleting_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initialising voice input.
        /// </summary>
        internal static string Error_initialising_voice_input {
            get {
                return ResourceManager.GetString("Error_initialising_voice_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing audio capture.
        /// </summary>
        internal static string Error_initializing_audio_capture_ {
            get {
                return ResourceManager.GetString("Error_initializing_audio_capture_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading files for .
        /// </summary>
        internal static string Error_loading_files_for_ {
            get {
                return ResourceManager.GetString("Error_loading_files_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading model.
        /// </summary>
        internal static string Error_loading_model {
            get {
                return ResourceManager.GetString("Error_loading_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading VAD model.
        /// </summary>
        internal static string Error_loading_VAD_model_ {
            get {
                return ResourceManager.GetString("Error_loading_VAD_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Whisper model.
        /// </summary>
        internal static string Error_loading_Whisper_model_ {
            get {
                return ResourceManager.GetString("Error_loading_Whisper_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file: {0}.
        /// </summary>
        internal static string Error_reading_file___0_ {
            get {
                return ResourceManager.GetString("Error_reading_file___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error regenerating message.
        /// </summary>
        internal static string Error_regenerating_message {
            get {
                return ResourceManager.GetString("Error_regenerating_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting system prompt.
        /// </summary>
        internal static string Error_setting_system_prompt {
            get {
                return ResourceManager.GetString("Error_setting_system_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting voice input.
        /// </summary>
        internal static string Error_starting_voice_input {
            get {
                return ResourceManager.GetString("Error_starting_voice_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Whisper model not found.
        /// </summary>
        internal static string Error_Whisper_model_not_found {
            get {
                return ResourceManager.GetString("Error_Whisper_model_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert a token.
        /// </summary>
        internal static string Failed_to_convert_a_token_ {
            get {
                return ResourceManager.GetString("Failed_to_convert_a_token_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory: {0}.
        /// </summary>
        internal static string Failed_to_create_directory___0_ {
            get {
                return ResourceManager.GetString("Failed_to_create_directory___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the model context.
        /// </summary>
        internal static string Failed_to_create_the_model_context_ {
            get {
                return ResourceManager.GetString("Failed_to_create_the_model_context_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the sampler.
        /// </summary>
        internal static string Failed_to_create_the_sampler_ {
            get {
                return ResourceManager.GetString("Failed_to_create_the_sampler_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to tokenize the prompt.
        /// </summary>
        internal static string Failed_to_tokenize_the_prompt_ {
            get {
                return ResourceManager.GetString("Failed_to_tokenize_the_prompt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First token time: .
        /// </summary>
        internal static string First_token_time__ {
            get {
                return ResourceManager.GetString("First_token_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found.
        /// </summary>
        internal static string Folder_not_found {
            get {
                return ResourceManager.GetString("Folder_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        internal static string Generation {
            get {
                return ResourceManager.GetString("Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStateData.
        /// </summary>
        internal static string GetStateData {
            get {
                return ResourceManager.GetString("GetStateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History is not configured..
        /// </summary>
        internal static string History_is_not_configured_ {
            get {
                return ResourceManager.GetString("History_is_not_configured_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Error loading files for .
        /// </summary>
        internal static string HTTP_Error_loading_files_for_ {
            get {
                return ResourceManager.GetString("HTTP_Error_loading_files_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jinja template file not found
        ///
        ///.
        /// </summary>
        internal static string Jinja_template_file_not_found__ {
            get {
                return ResourceManager.GetString("Jinja_template_file_not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Parse Error for .
        /// </summary>
        internal static string JSON_Parse_Error_for_ {
            get {
                return ResourceManager.GetString("JSON_Parse_Error_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LM Stud.
        /// </summary>
        internal static string LM_Stud {
            get {
                return ResourceManager.GetString("LM_Stud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LM_Stud_256 {
            get {
                object obj = ResourceManager.GetObject("LM_Stud_256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a local chat slot and a separate loaded local slot marked Dialectic before enabling dialectic mode..
        /// </summary>
        internal static string Load_a_local_chat_slot_and_a_ {
            get {
                return ResourceManager.GetString("Load_a_local_chat_slot_and_a_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a model first..
        /// </summary>
        internal static string Load_a_model_first_ {
            get {
                return ResourceManager.GetString("Load_a_model_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load main.
        /// </summary>
        internal static string Load_main {
            get {
                return ResourceManager.GetString("Load_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Model.
        /// </summary>
        internal static string Load_Model {
            get {
                return ResourceManager.GetString("Load_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Slot.
        /// </summary>
        internal static string Load_Slot {
            get {
                return ResourceManager.GetString("Load_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        internal static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading: .
        /// </summary>
        internal static string Loading__ {
            get {
                return ResourceManager.GetString("Loading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum context size of the last loaded model: .
        /// </summary>
        internal static string Max_context_size_of_last_loaded_model {
            get {
                return ResourceManager.GetString("Max_context_size_of_last_loaded_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP.
        /// </summary>
        internal static string MCP {
            get {
                return ResourceManager.GetString("MCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP command is required when the MCP slot is enabled as a tool..
        /// </summary>
        internal static string MCP_command_is_required_when_the_MCP_slot_is_enabled_as_a_tool_ {
            get {
                return ResourceManager.GetString("MCP_command_is_required_when_the_MCP_slot_is_enabled_as_a_tool_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP Connect.
        /// </summary>
        internal static string MCP_Connect {
            get {
                return ResourceManager.GetString("MCP_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP Disconnect.
        /// </summary>
        internal static string MCP_Disconnect {
            get {
                return ResourceManager.GetString("MCP_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP URL is required when the MCP slot is enabled as a tool..
        /// </summary>
        internal static string MCP_URL_is_required_when_the_MCP_slot_is_enabled_as_a_tool_ {
            get {
                return ResourceManager.GetString("MCP_URL_is_required_when_the_MCP_slot_is_enabled_as_a_tool_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model file not found
        ///
        ///.
        /// </summary>
        internal static string Model_File_Not_Found {
            get {
                return ResourceManager.GetString("Model_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model search error: {0}.
        /// </summary>
        internal static string Model_search_error___0_ {
            get {
                return ResourceManager.GetString("Model_search_error___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models folder not found.
        /// </summary>
        internal static string Models_folder_not_found {
            get {
                return ResourceManager.GetString("Models_folder_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models folder not found, please specify a valid folder in the Settings tab..
        /// </summary>
        internal static string Models_folder_not_found_ {
            get {
                return ResourceManager.GetString("Models_folder_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Jinja chat template was found in the selected model..
        /// </summary>
        internal static string No_Jinja_chat_template_was_found_in_the_selected_model_ {
            get {
                return ResourceManager.GetString("No_Jinja_chat_template_was_found_in_the_selected_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model has been loaded..
        /// </summary>
        internal static string No_model_has_been_loaded_ {
            get {
                return ResourceManager.GetString("No_model_has_been_loaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model loaded.
        /// </summary>
        internal static string No_model_loaded {
            get {
                return ResourceManager.GetString("No_model_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only local slots can be unloaded..
        /// </summary>
        internal static string Only_local_slots_can_be_unloaded_ {
            get {
                return ResourceManager.GetString("Only_local_slots_can_be_unloaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid API base URL.
        /// </summary>
        internal static string Please_enter_a_valid_API_base_URL {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_API_base_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item from both lists..
        /// </summary>
        internal static string Please_select_an_item_from_both_lists_ {
            get {
                return ResourceManager.GetString("Please_select_an_item_from_both_lists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prompt is required.
        /// </summary>
        internal static string prompt_is_required {
            get {
                return ResourceManager.GetString("prompt_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate limit exceeded.
        /// </summary>
        internal static string Rate_limit_exceeded {
            get {
                return ResourceManager.GetString("Rate_limit_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid response from the API server.
        /// </summary>
        internal static string Received_an_invalid_response_from_the_API_server {
            get {
                return ResourceManager.GetString("Received_an_invalid_response_from_the_API_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the {0} slot?.
        /// </summary>
        internal static string Remove_the__0__slot_ {
            get {
                return ResourceManager.GetString("Remove_the__0__slot_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated tool calls detected.
        /// </summary>
        internal static string Repeated_tool_calls_detected {
            get {
                return ResourceManager.GetString("Repeated_tool_calls_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset chat.
        /// </summary>
        internal static string Reset_chat {
            get {
                return ResourceManager.GetString("Reset_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retokenizing chat....
        /// </summary>
        internal static string Retokenizing_chat___ {
            get {
                return ResourceManager.GetString("Retokenizing_chat___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a local or MCP slot first..
        /// </summary>
        internal static string Select_a_local_or_MCP_slot_first_ {
            get {
                return ResourceManager.GetString("Select_a_local_or_MCP_slot_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a model first..
        /// </summary>
        internal static string Select_a_model_first_ {
            get {
                return ResourceManager.GetString("Select_a_model_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a slot first..
        /// </summary>
        internal static string Select_a_slot_first_ {
            get {
                return ResourceManager.GetString("Select_a_slot_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetState
        ///
        ///state is null.
        /// </summary>
        internal static string SetState__State_is_null {
            get {
                return ResourceManager.GetString("SetState__State_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetStateData.
        /// </summary>
        internal static string SetStateData {
            get {
                return ResourceManager.GetString("SetStateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot name is required..
        /// </summary>
        internal static string Slot_name_is_required_ {
            get {
                return ResourceManager.GetString("Slot_name_is_required_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active API model slot is incomplete..
        /// </summary>
        internal static string The_active_API_model_slot_is_incomplete_ {
            get {
                return ResourceManager.GetString("The_active_API_model_slot_is_incomplete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API request timed out.
        /// </summary>
        internal static string The_API_request_timed_out {
            get {
                return ResourceManager.GetString("The_API_request_timed_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API request was canceled before completion.
        /// </summary>
        internal static string The_API_request_was_canceled_before_completion {
            get {
                return ResourceManager.GetString("The_API_request_was_canceled_before_completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API server encountered an error.
        /// </summary>
        internal static string The_API_server_encountered_an_error {
            get {
                return ResourceManager.GetString("The_API_server_encountered_an_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chat template could not be applied..
        /// </summary>
        internal static string The_chat_template_could_not_be_applied_ {
            get {
                return ResourceManager.GetString("The_chat_template_could_not_be_applied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPU is out of memory..
        /// </summary>
        internal static string The_GPU_is_out_of_memory_ {
            get {
                return ResourceManager.GetString("The_GPU_is_out_of_memory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main slot cannot be removed. Edit it instead..
        /// </summary>
        internal static string The_main_slot_cannot_be_removed__Edit_it_instead_ {
            get {
                return ResourceManager.GetString("The_main_slot_cannot_be_removed__Edit_it_instead_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main slot must be a local or API chat slot. Add MCP servers as separate tool slots..
        /// </summary>
        internal static string The_main_slot_must_be_a_local_or_API_chat_slot__ {
            get {
                return ResourceManager.GetString("The_main_slot_must_be_a_local_or_API_chat_slot__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model backend returned a decode error..
        /// </summary>
        internal static string The_model_backend_returned_a_decode_error_ {
            get {
                return ResourceManager.GetString("The_model_backend_returned_a_decode_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model could not be loaded..
        /// </summary>
        internal static string The_model_could_not_be_loaded_ {
            get {
                return ResourceManager.GetString("The_model_could_not_be_loaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model is not in the current Models list. Refresh the list or check the Models folder.
        ///
        ///.
        /// </summary>
        internal static string The_model_is_not_in_the_current_models_list__ {
            get {
                return ResourceManager.GetString("The_model_is_not_in_the_current_models_list__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modified settings are overridden by the Model Settings for this model..
        /// </summary>
        internal static string The_modified_settings_are_overridden_ {
            get {
                return ResourceManager.GetString("The_modified_settings_are_overridden_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Call.
        /// </summary>
        internal static string Tool_Call {
            get {
                return ResourceManager.GetString("Tool_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool call output requires a call_id..
        /// </summary>
        internal static string Tool_call_output_requires_a_call_id_ {
            get {
                return ResourceManager.GetString("Tool_call_output_requires_a_call_id_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Output.
        /// </summary>
        internal static string Tool_Output {
            get {
                return ResourceManager.GetString("Tool_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the API server.
        /// </summary>
        internal static string Unable_to_connect_to_the_API_server {
            get {
                return ResourceManager.GetString("Unable_to_connect_to_the_API_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the chat message.
        /// </summary>
        internal static string Unable_to_parse_the_chat_message_ {
            get {
                return ResourceManager.GetString("Unable_to_parse_the_chat_message_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown API error.
        /// </summary>
        internal static string Unknown_API_error_ {
            get {
                return ResourceManager.GetString("Unknown_API_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload Slot.
        /// </summary>
        internal static string Unload_Slot {
            get {
                return ResourceManager.GetString("Unload_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string URL_ {
            get {
                return ResourceManager.GetString("URL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using API Model: .
        /// </summary>
        internal static string Using_API_Model_ {
            get {
                return ResourceManager.GetString("Using_API_Model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Model: .
        /// </summary>
        internal static string Using_Model_ {
            get {
                return ResourceManager.GetString("Using_Model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using slot .
        /// </summary>
        internal static string Using_slot_ {
            get {
                return ResourceManager.GetString("Using_slot_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAD model not found, use Basic VAD?.
        /// </summary>
        internal static string VAD_model_not_found__use_Basic_VAD_ {
            get {
                return ResourceManager.GetString("VAD_model_not_found__use_Basic_VAD_", resourceCulture);
            }
        }
    }
}
